# Generated by Django 2.1.7 on 2019-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=1)),
                ('event_id', models.ForeignKey(on_delete=None, related_name='event_id', to='events.Event')),
            ],
        ),
    ]
