# Generated by Django 2.1.7 on 2019-03-22 06:16

import api.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('firebase_reg_token', models.CharField(blank=True, default='', max_length=256)),
                ('ical_key', models.CharField(blank=True, default=api.users.models.gen_ical_key, editable=False, max_length=24, unique=True)),
            ],
        ),
    ]
