# Generated by Django 2.1.7 on 2019-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of your Event', max_length=256)),
                ('event_date', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('event_time', models.TimeField(blank=True, help_text='HH:MM', null=True)),
                ('event_duration', models.TimeField(blank=True, default=None, help_text='Length of Event in HH:MM', null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(default=None, help_text='Miscellaneous notes or details you wish to include')),
            ],
        ),
    ]
