# Generated by Django 2.1.7 on 2019-03-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_admin', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.ForeignKey(on_delete=None, related_name='location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.UserProfile'),
        ),
    ]
