# Generated by Django 2.1.7 on 2019-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_uses', models.PositiveIntegerField(auto_created=True, default=0)),
                ('street_address', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
